#!/bin/sh

OutFile='npm/lib/knockout.js'
PackageFile='npm/package.json'

Version=`cat src/build/fragments/version.txt`
VersionHeaderPath='src/build/fragments/version-header.js'
VersionJsPath='src/src/version.js'
sed "s/##VERSION##/$Version/" <$VersionHeaderPath > $VersionHeaderPath.temp
sed "s/Working-Debug/$Version/" <$VersionJsFile > $VersionJsFile.temp

# Combine the source files
SourceFiles=`grep js < src/build/fragments/source-references.js | # Find JS references 
             sed "s/[ \',]//g" |              # Strip off JSON fluff (whitespace, commas, quotes)
             sed -e 's/.*/src\/&/' |          # Fix the paths by prefixing with ../
             sed "s/version\.js/version\.js\.temp/" |    # Use a temporary version with correct version number
             tr '\n' ' '`                     # Combine into single line
cat src/build/fragments/amd-pre.js                     >  $OutFile.temp
cat $SourceFiles                                       >> $OutFile.temp
cat src/build/fragments/amd-post.js                    >> $OutFile.temp

# Finalise file by prefixing with version header and surrounding in function closure
# cp src/build/fragments/version-header.js $OutFile
cat $VersionHeaderPath.temp                            >  $OutFile
cat node-npm-header.js                                 >> $OutFile
echo "(function(window,document,navigator,undefined){" >> $OutFile
cat $OutFile.temp                                      >> $OutFile
echo "})(window,document,navigator);"                  >> $OutFile
rm -rf $OutFile.temp
rm -rf $VersionHeaderPath.temp

rm -rf $PackageFile

echo "{"                                                                     >  $PackageFile
echo "  \"name\"          : \"knockout\","                                   >> $PackageFile
echo "  \"version\"       : \""$Version"\","                                 >> $PackageFile
echo "  \"description\"   : \"NodeJs Testable version of client script which Simplifies Dynamic JavaScript UIs by applying the Model-View-ViewModel (MVVM) Pattern.\"," >> $PackageFile
echo "  \"repository\"    : {"                                               >> $PackageFile
echo "    \"type\"        : \"git\","                                        >> $PackageFile
echo "    \"url\"         : \"https://github.com/mtscout6/knockout-node\","  >> $PackageFile
echo "  },"                                                                  >> $PackageFile
echo "  \"keywords\"      : [\"testing\", \"mvvm\"],"                        >> $PackageFile
echo "  \"author\"        : \"Steven Sanderson\","                           >> $PackageFile
echo "  \"contributors\"  : [\"Matthew Smith <mtscout6@gmail.com>\"],"       >> $PackageFile
echo "  \"maintainers\"   : \"Matthew Smith <mtscout6@gmail.com>\","         >> $PackageFile
echo "  \"licenses\"      : [\"MIT\"],"                                      >> $PackageFile
echo "  \"dependencies\"  : {\"jsdom\" : \">=0.2.8\"},"                      >> $PackageFile
echo "  \"main\"          : \"bin/knockout\""                                >> $PackageFile
echo "}"                                                                     >> $PackageFile
